import Head from "next/head";
import styles from "@/pages/styles.module.css";
import {data} from "@/utils/getSeatMap";
import classnames from 'classnames'
import { useEffect, useState } from "react";

export default function Home() {
  const seatMap = data
  const [seatDataMap, setSeatDataMap] = useState({})


  const [numSeats, setNumOfSeats] = useState(3);

  useEffect(()=>{
    getSeatDataByCategory();
  },[])


  const getSeatDataByCategory = () => {
    const categoryMap = {}, seatDataMap = {};
    seatMap.categoryData.forEach(item => {
      categoryMap[item.areaCode] = item.areaName;
    })

    seatMap.seatData.forEach(item => {
      const areaName = categoryMap[item.areaCode]
      if(seatDataMap[areaName]) {
        seatDataMap[areaName].push(item)
      } else {
        seatDataMap[areaName] = [item]
      }
    })
    setSeatDataMap(seatDataMap);
  }

  const selectSeats = (areaName,rowCode,seatNo, seats) => {
    const seatIndex = seats.findIndex(item => item.seatNo === seatNo);
    const seatDataMapTemp = {...seatDataMap};
    for(let i=0; i< numSeats; i++) {
      if(seats[seatIndex].isAvail) {
        seats[seatIndex].isSelected = true;
      } else {
        break;
      }
    }
    seatDataMapTemp[areaName].seats = seats;
    setSeatDataMap({...seatDataMapTemp});
  }
  return (
    <>
      <Head>
        <title>Book my Show</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={styles.page}
      >

        <div>
          <div className={styles.numSelector}>
              <span>How many seats do you want?</span>
              <div>{
                  [...new Array(9)]
                      .map((_, i) =>
                          <div
                              key={i}
                              className={classnames(styles.seat,  (i + 1) === numSeats &&  styles.selected)}
                              onClick={()=>setNumOfSeats(i+1)}
                          >
                              {i + 1}
                          </div>
                      )}
              </div>
          </div>
        </div>

        <div className={styles.map}>
          {Object.keys(seatDataMap).map(item => {
              return <>
                <span>{item}</span>
                {seatDataMap[item].map(({rowCode, seats}) => {
                  return <div>
                      <span className={styles.seats}>
                          <span className={classnames(styles.rowName, styles.seat)}>{rowCode}</span>
                          {seats.map((seat, i) => {
                            return (
                                <div
                                    key={⁠ ${i}-${rowCode} ⁠}
                                    className={classnames(styles.seat, seat.isWalkway && styles.walkway, seat.isPreferred && styles.preferred, !seat.isAvail && styles.booked, seat.isSelected && styles.selected)}
                                    onClick={()=>selectSeats(item, rowCode, seat.seatNo, seats)}
                                >
                                  {seat.seatNo}
                                </div>
                            )
                          })}
                      </span>
                  </div>
                })}
              </>
            })}
        </div>

        <div className={styles.legendContainer}>
          <div className={styles.legend}>Selected: <div className={classnames(styles.seat, styles.selected)}></div></div>
          <div className={styles.legend}>Booked: <div className={classnames(styles.seat, styles.booked)}></div></div>
          <div className={styles.legend}>Preferred: <div className={classnames(styles.seat, styles.preferred)}></div></div>
        </div>

      </div>
    </>
  );
}